TSNAMES = demo judgments miscellaneous foo interpretations judged-expressions theorem-binders ts-elf ts-elf-2 show semi-intrinsic
TSFILES = $(patsubst %,test/%.ts,$(TSNAMES))
all: tests
tests : $(TSNAMES)
$(TSNAMES): src/$(CHECKER_EXE) ; $(CHECKER) test/$@.ts

#  Local Variables:
#  compile-command: "make -C .. tests "
#  End:
