TSNAMES = demo test test2 test3 test4 test5 ts-elf
TSFILES = $(patsubst %,test/%.ts,$(TSNAMES))
all: tests
tests : $(TSNAMES)
$(TSNAMES): src/$(CHECKER_EXE) ; $(CHECKER) test/$@.ts

#  Local Variables:
#  compile-command: "make -C .. tests "
#  End:
