TSNAMES = demo judgments miscellaneous foo interpretations intrinsic theorem-binders ts-elf show witnessed-judgments plus
TSFILES = $(patsubst %,test/%.ts,$(TSNAMES))
all: tests
tests : $(TSNAMES)
$(TSNAMES): src/$(CHECKER_EXE) ; $(CHECKER) $(TSFLAGS) test/$@.ts

#  Local Variables:
#  compile-command: "make -C .. tests "
#  End:
