TACTIC_FILENAMES = tactics ev3 tn witness default assumption fail admit shuffle tscheck
TACTIC_FILES = $(patsubst %, src/tactics/%.ml, $(TACTIC_FILENAMES))

# Local Variables:
# compile-command: "make -C ../.. build "
# End:

