TS_RULES = abbreviations TS TS0 TS1 TS2 TS3 TS4 TS5 TS6 TS7 others
HTS_RULES = TTS

define rules-m
$(foreach x,$2, \
	$(eval TAGS_FILES += rules/$x.ts) \
	$(eval check tests $1: test-rules-$x.ts) \
	$(eval $x test-rules-$x.ts: src/$(CHECKER_EXE) ; $(CHECKER) rules/$x.ts))
endef

$(call rules-m,ts-rules,$(TS_RULES))
$(call rules-m,hts-rules,$(HTS_RULES))

#  Local Variables:
#  compile-command: "make -C .. "
#  End:
